### PR TITLE
POST-FREEZE: Libcloud Super Class!

### PR DESCRIPTION
**Pull request by hinesmr**
This is a major commit for libcloud-based adapters: This creates a super class
around libcloud so that new libcloud-based clouds can be added with the absolute
minimalist of changes. With this commit, Azure and Alibaba should be SUPER easy now.

@bowers in particular:

We've introduced a base function named "pre_vmcreate" which allows special cases,
like VCloud to tweak things if necessary.

Obviously, I don't have access to VCloud, so I need someone else to test it for me.

This commit also changes your credentials in the configuration file from using a semicolon to separate the username and password to a colon (instead of a semi-colon). I would definitely need you to test this before I could merge it.

### CODE REVIEW

**Comment by hinesmr** [comment]
@maugustosilva @salmanbaset This PR has been tested successfully by both myself (DigitalOcean) and VCloud (@bowers ). 

Ready for merge whenever you guys see fit.

**Comment by salmanbaset** [comment]
actually, can you confirm if you did a simulated cloud SPEC Cloud run with the changes?

**Comment by hinesmr** [comment]
Sure, I'll do that in the morning.

**Comment by salmanbaset** [comment]
tested and working correctly. merging.

**Pull request merged**
