### PR TITLE
Dockerfile-ubuntu: explicitly install sudo,net-tools; supress console…

### PR DESCRIPTION
**Pull request by Leonid99**
… in postinst scriptlets

### CODE REVIEW

**Comment by hinesmr** [comment]
@psuriset Comments?

**Comment by psuriset** [comment]
sure. let me change it

**Comment by Leonid99** [comment]
@psuriset The original commit probably meant to delete `Dockerfile`, because `Dockerfile` and `Dockerfile-ubuntu` are identical.

**Comment by psuriset** [comment]
@Leonid99  yes

**Comment by psuriset** [comment]
@Leonid99 I cleaned up the older Dockerfile. Let me know if you its fine for you.

**Pull request merged**
