### PR TITLE
s/async/nosync for Python 3.8

### PR DESCRIPTION
**Pull request by mraygalaxy**
I believe I've converted everything and also included
command-line-level backwards compatibility (only) for 'async',
just because old habits die hard.

But, anything that uses the API will need to switchover.

### CODE REVIEW

**Comment by mraygalaxy** [comment]
@jdesfossez  @maugustosilva  How does this look? Would you like to test the branch first?

**Comment by jdesfossez** [comment]
Hi Michael, thanks for this PR !
We just tested it on Python 3.8 and it works perfectly !

**Comment by mraygalaxy** [comment]
Perfect, glad to hear it. @maugustosilva This is a pretty impactful change. Any objections?

**Comment by mraygalaxy** [comment]
@jdesfossez Marcio sounds a little busy right now, but I doubt he'd have any objections here. I'll go ahead and merge this as well.

**Pull request merged**
